### ISSUE TITLE
mysql_user module failing with "'database' is an invalid keyword argument for this function"

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/ansible.mysql#151]
##### SUMMARY

I haven't changed anything in my role, and I looked through the changelog for this collection, and I can't find anything that indicates I'm doing something wrong, so I figured I'd open a bug report here; my CI tests just started failing after Ansible 3.3.0 came out and was used for CI runs starting yesterday.

The failure is on this task:

```yaml
- name: Remove anonymous MySQL users.
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: "{{ mysql_anonymous_hosts.stdout_lines|default([]) }}"
```

And the failure message:

```
TASK [geerlingguy.mysql : Remove anonymous MySQL users.] ***********************
failed: [instance] (item=instance) => {"ansible_loop_var": "item", "changed": false, "item": "instance", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
failed: [instance] (item=localhost) => {"ansible_loop_var": "item", "changed": false, "item": "localhost", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
```

I'm not passing `database` anywhere, so I'm not quite sure what's going wrong...

Related: https://github.com/geerlingguy/ansible-role-mysql/issues/445

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/jgeerling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 24 2021, 13:26:09) [Clang 12.0.0 (clang-1200.0.32.29)]
```

(I have 3.3.0 installed according to Pip... I guess it's just showing the ansible-base version I have installed locally?)

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/Users/jgeerling/Dropbox/VMs/roles']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS (locally)
Ubuntu 20.04 (GitHub Actions CI)

##### STEPS TO REPRODUCE

See task above in summary.

##### EXPECTED RESULTS

mysql_user should succeed as it has before.

##### ACTUAL RESULTS

See error message above in summary.

**Comment by Andersson007** [comment]
@geerlingguy hi, thanks for reporting this! https://github.com/ansible-collections/community.mysql/pull/116
could you please update the db driver version on your system to let your tests pass while we're working on this.

**Comment by Andersson007** [comment]
@geerlingguy I've just released fixed version 2.1.0 and 1.4.1. Available on galaxy

**Comment by mamono210** [comment]
Thanks to this fix, my Playbook is working again!

Thank you very much!

**Comment by Andersson007** [comment]
@TomonoriMatsumura you and the community are welcome:)

**Comment by Andersson007** [comment]
As it's confirmed that the fix helps, I'll close the issue. Thanks everyone!

**Comment by ksarunas** [comment]
I am on `ansible 2.10.9` and I am still receiving the same error:
```
fatal: [host]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
```

task:
```
- name: Ensure {{ mysql_user }} is present
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    state: present
```

**Comment by Andersson007** [comment]
@ksarunas Ansible release is planned tomorrow (on May 11) but I don't know the exact time, so you could try to upgrade, say, on May 12 and give us feedback. Alternatively, you could install the latest version of the collection manually using `ansible-galaxy`, see the manual [here](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html). In any case, please give us the feedback.
Thanks

**Comment by ksarunas** [comment]
I can confirm that on `2.11.0` issue is fixed 👍  thank you!

**Comment by Andersson007** [comment]
@ksarunas thanks for the feedback!
